#!/usr/bin/env bash
#pings an ip address passed as an argument
if [ $# -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

echo "Pinging $ip_address 5 times..."

ping -c 5 "$ip_address"
